name: docs

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
      - microsite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install and publish
        run: |
          echo "Actor: ${GITHUB_ACTOR}"
          echo "machine github.com login ${GITHUB_ACTOR} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          cd docs/docus/website
          npm install && GIT_USER="${GITHUB_ACTOR}" CURRENT_BRANCH= npm run publish-gh-pages
